repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        args: [--safe]
        language_version: python3.7
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-vcs-permalinks
    -   id: trailing-whitespace
    -   id: fix-encoding-pragma
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: check-yaml
    -   id: flake8
        additional_dependencies: ["flake8-bugbear == 19.8.0"]
        language_version: python3.7
        log_file: flake8.log
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.3
    hooks:
    -   id: seed-isort-config
        args: [--application-directories, "yomiel:."]
-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
    -   id: isort
        exclude: ^setup\.py$|Message\.proto$
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.25.1
    hooks:
    -   id: pyupgrade
